require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/support/*.rb'
    - 'spec/*.rb'
    - 'bin/**/*/'

Layout/HashAlignment:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Rails/EnumHash:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/OpenStructUse:
  Enabled: false
